nextflow-io/website

- content/blog/2021/5_tips_for_hpc_users.md
Incorporating the final changes.
> updates to blog post

- content/demo.nf
- content/example1.md
- content/example2.md
- content/example3.md
- content/example4.md
Resolves #40 
This PR updates the workflow examples to DSL2.
> Update pipeline examples to DSL2

- content/blog/2022/nextflow-summit-call-for-abstracts.md
- templates/archive.ftl
My local testing setup is now refusing to launch, so maybe worth double checking that this renders properly if possible.
After I added the links, the blog listing page was chopping up the button and giving weird effects. I tried adjusting the word limit cutoff but now can't test to see if I got it right 🤦🏻 
Hopefully it's ok..?? 🤞🏻
> Actually add buttons for the CFA on the summit page

- assets/docs/edge/getstarted.html
- assets/docs/latest/getstarted.html
- content/index.html
Fix small typo and fix link to point it to correct section.
> Typo link fix

- assets/docs/edge/_sources/process.rst.txt
- assets/docs/edge/_sources/process.txt
- assets/docs/edge/process.html
Fix typo in process documentation.
> DOC: Fix typo in process documentation

- content/blog/2022/turbocharging-nextflow-with-fig.md
Minor changes to the blog post that I didn't notice earlier.
> Update fig blogpost

- content/about-us.html
This PR seeks to update the [About us](https://www.nextflow.io/about-us.html) page in the website.
- Improves slightly the wording in _About Nextflow_
- Updates info about individuals that are mentioned
> Update `about us` page

- assets/css/custom.css
- content/blog/2023/learn-nextflow-in-2023.md
- templates/menu.ftl
> content: fix blog table of contents

- content/slack-invite.html
> Update Slack invite link

- content/our_ambassadors.html
Multiple minor updates to the ambassador's list page.
> Updates to the ambassadors page list

- astro.config.mjs
- src/pages/blog/index.astro
can't push directly to the other branch, but here my changes as a PR.
> render markdown to extract description

- src/content/blog/2024/nf-test-in-nf-core.md
- src/content/blog/2024/nxf-nf-core-workshop-kogo.md
Signed-off-by: Marcel Ribeiro-Dantas <mribeirodantas@seqera.io>
> Improve top box for community blog posts

- src/layouts/Layout.astro
> Remove duplicate `<meta>` description.

- src/pages/slack-invite.astro
Signed-off-by: Marcel Ribeiro-Dantas <mribeirodantas@seqera.io>
> Update Slack link

- src/pages/our_ambassadors.astro
Signed-off-by: Marcel Ribeiro-Dantas <mribeirodantas@seqera.io>
> Add alumni section with alumni ambassadors

- src/pages/our_ambassadors.astro
> Minor fixes to Our Ambassadors page

- src/pages/our_ambassadors.astro
Signed-off-by: Marcel Ribeiro-Dantas <mribeirodantas@seqera.io>
> Add anchors to Our Ambassadors sections

- package-lock.json
- package.json
Should have no effect on the website, just keeping things up to date.
> Astro: update packages

- src/pages/podcast/[...episode].astro
@netlify /podcast/2024/ep44_regulatory.html
> Podcast: YouTube video now full width and responsive

- src/components/QuickInstaller/index.tsx
- src/pages/index.astro
I know that there is a copy revamp coming, but couldn't resist putting in a few minor tweaks here and there.
> Minor tweaks to language on new homepage

- src/components/QuickInstaller/index.tsx
- src/pages/blast-pipeline.md
- src/pages/machine-learning-pipeline.md
- src/pages/rna-seq-pipeline.md
This PR bumps Java 17 as min requirements for Nextflow
> Bump Java 17 as min version
